<script>
const routes = [
  { path: '*', component: resolve => require(['@/components/error404'], resolve) },
  { path: '/admin', component: resolve => require(['@/views/login'], resolve) },
  { path: '/error', component: resolve => require(['@/components/error'], resolve) },
  { path: '/error404', component: resolve => require(['@/components/error404'], resolve) },
  { path: '/admin/dashboard/home', component: resolve => require(['@/views/home'], resolve) },
  { path: '/admin/common/system/SystemApiControl', component: resolve => require(['@/views/common/system/SystemApiControl'], resolve) },
  { path: '/admin/common/system/GroupControl', component: resolve => require(['@/views/common/system/GroupControl'], resolve) },
  { path: '/admin/common/system/OperatorControl', component: resolve => require(['@/views/common/system/OperatorControl'], resolve) },
  { path: '/admin/common/system/UserProfile', component: resolve => require(['@/views/common/system/UserProfile'], resolve) },
  { path: '/admin/common/system/OperationPasswordControl', component: resolve => require(['@/views/common/system/OperationPasswordControl'], resolve) },
  { path: '/admin/test', component: resolve => require(['@/views/Test'], resolve) },
  { path: '/admin/zhongtan/configuration/PortConfig', component: resolve => require(['@/views/zhongtan/configuration/PortConfig'], resolve) },
  { path: '/admin/zhongtan/configuration/VesselConfig', component: resolve => require(['@/views/zhongtan/configuration/VesselConfig'], resolve) },
  { path: '/admin/zhongtan/configuration/VoyageConfig', component: resolve => require(['@/views/zhongtan/configuration/VoyageConfig'], resolve) },
  {
    path: '/admin/zhongtan/configuration/ContainerManagerConfig',
    component: resolve => require(['@/views/zhongtan/configuration/ContainerManagerConfig'], resolve)
  },
  { path: '/admin/zhongtan/configuration/Customer', component: resolve => require(['@/views/zhongtan/configuration/Customer'], resolve) },
  { path: '/admin/zhongtan/configuration/CustomerAdmin', component: resolve => require(['@/views/zhongtan/configuration/CustomerAdmin'], resolve) },
  { path: '/admin/zhongtan/configuration/Employee', component: resolve => require(['@/views/zhongtan/configuration/Employee'], resolve) },
  {
    path: '/admin/zhongtan/configuration/BillladingNoConfig',
    component: resolve => require(['@/views/zhongtan/configuration/BillladingNoConfig'], resolve)
  },
  { path: '/admin/zhongtan/export/Booking', component: resolve => require(['@/views/zhongtan/export/Booking'], resolve) },
  { path: '/admin/zhongtan/export/BookingWork', component: resolve => require(['@/views/zhongtan/export/BookingWork'], resolve) },
  { path: '/admin/zhongtan/export/Receipt', component: resolve => require(['@/views/zhongtan/export/Receipt'], resolve) },
  { path: '/admin/zhongtan/export/BookingLoad', component: resolve => require(['@/views/zhongtan/export/BookingLoad'], resolve) },
  { path: '/admin/zhongtan/export/CommercialVerification', component: resolve => require(['@/views/zhongtan/export/CommercialVerification'], resolve) },
  { path: '/admin/zhongtan/export/BusinessVerification', component: resolve => require(['@/views/zhongtan/export/BusinessVerification'], resolve) },
  { path: '/admin/zhongtan/export/ShipmentRelease', component: resolve => require(['@/views/zhongtan/export/ShipmentRelease'], resolve) },
  { path: '/admin/zhongtan/export/ShipmentReceipt', component: resolve => require(['@/views/zhongtan/export/ShipmentReceipt'], resolve) },
  { path: '/admin/zhongtan/import/ImportWork', component: resolve => require(['@/views/zhongtan/import/ImportWork'], resolve) },
  { path: '/admin/zhongtan/invoice/Invoice', component: resolve => require(['@/views/zhongtan/invoice/Invoice'], resolve) },
  { path: '/admin/zhongtan/invoice/InvoiceReceipt', component: resolve => require(['@/views/zhongtan/invoice/InvoiceReceipt'], resolve) },
  { path: '/admin/zhongtan/invoice/ManagerCheck', component: resolve => require(['@/views/zhongtan/invoice/ManagerCheck'], resolve) },
  { path: '/admin/zhongtan/invoice/BusinessCheck', component: resolve => require(['@/views/zhongtan/invoice/BusinessCheck'], resolve) },
  { path: '/admin/zhongtan/invoice/InvoiceSearch', component: resolve => require(['@/views/zhongtan/invoice/InvoiceSearch'], resolve) },
  { path: '/admin/zhongtan/invoice/InvoiceStatistics', component: resolve => require(['@/views/zhongtan/invoice/InvoiceStatistics'], resolve) },
  { path: '/admin/zhongtan/web/SailSchedule', component: resolve => require(['@/views/zhongtan/web/SailSchedule'], resolve) },
  { path: '/admin/zhongtan/web/WebConfig', component: resolve => require(['@/views/zhongtan/web/WebConfig'], resolve) },
  { path: '/admin/zhongtan/fee/InvoiceDefaultFee', component: resolve => require(['@/views/zhongtan/fee/InvoiceDefaultFee'], 
  resolve) },
  { path: '/admin/zhongtan/fee/CustomerFixedDeposit', component: resolve => require(['@/views/zhongtan/fee/CustomerFixedDeposit'], 
  resolve) },
  { path: '/admin/zhongtan/fee/CustomerFixedReceipt', component: resolve => require(['@/views/zhongtan/fee/CustomerFixedReceipt'], 
  resolve) },
  { path: '/admin/zhongtan/fee/ExportFeeData', component: resolve => require(['@/views/zhongtan/fee/ExportFeeData'], 
  resolve) },
  { path: '/admin/zhongtan/configuration/IcdConfig', component: resolve => require(['@/views/zhongtan/configuration/IcdConfig'], resolve) },
  { path: '/admin/zhongtan/configuration/ContainerSizeTypeConfig', component: resolve => require(['@/views/zhongtan/configuration/ContainerSizeTypeConfig'], resolve) },
  { path: '/admin/zhongtan/configuration/DischargePortConfig', component: resolve => require(['@/views/zhongtan/configuration/DischargePortConfig'], resolve) },
  { path: '/admin/zhongtan/equipment/OverdueCalculationConfig', component: resolve => require(['@/views/zhongtan/equipment/OverdueCalculationConfig'], resolve) },
  { path: '/admin/zhongtan/configuration/EdiDepotConfig', component: resolve => require(['@/views/zhongtan/configuration/EdiDepotConfig'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueCalculation', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueCalculation'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueCalculationReceipt', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueCalculationReceipt'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueCalculationSearch', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueCalculationSearch'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueCalculationAdmin', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueCalculationAdmin'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueCalculationReceiptAdmin', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueCalculationReceiptAdmin'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueCalculationSearchAdmin', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueCalculationSearchAdmin'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportOverdueStatistics', component: resolve => require(['@/views/zhongtan/equipment/ImportOverdueStatistics'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportDemurrageStatisticsInvoice', component: resolve => require(['@/views/zhongtan/equipment/ImportDemurrageStatisticsInvoice'], resolve) },
  { path: '/admin/zhongtan/equipment/ImportDemurrageStatisticsInvoiceAdmin', component: resolve => require(['@/views/zhongtan/equipment/ImportDemurrageStatisticsInvoiceAdmin'], resolve) },
  { path: '/admin/zhongtan/equipment/EmptyStockManagement', component: resolve => require(['@/views/zhongtan/equipment/EmptyStockManagement'], resolve) },
  { path: '/admin/zhongtan/equipment/ContainerMNRLedgerInvoice', component: resolve => require(['@/views/zhongtan/equipment/ContainerMNRLedgerInvoice'], resolve) },
  { path: '/admin/zhongtan/equipment/ContainerMNRLedgerReceipt', component: resolve => require(['@/views/zhongtan/equipment/ContainerMNRLedgerReceipt'], resolve) },
  { path: '/admin/zhongtan/equipment/ContainerMNRLedgerStatistics', component: resolve => require(['@/views/zhongtan/equipment/ContainerMNRLedgerStatistics'], resolve) },
]

export default routes
</script>
